---
- name: Install packages
  xbps:
    pkg:
      - xq-api
      - snooze
    state: present

- name: Configure xq-api
  template:
    src: xq-api.conf.j2
    dest: /etc/sv/xq-api/conf
    owner: root
    group: root
    mode: 0644
  notify:
    - xq-api

- name: Install xq-api HUP service (1/2)
  file:
    path: /etc/sv/xq-api-hup
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install xq-api HUP service (2/2)
  template:
    src: xq-api-hup.sh.j2
    dest: /etc/sv/xq-api-hup/run
    owner: root
    group: root
    mode: 0755
  notify:
    - xq-api-hup

- name: Create xq-api log directory
  file:
    path: /var/log/xq-api
    state: directory
    owner: _xqapi
    group: _xqapi
    mode: 0755

- name: Enable services
  runit:
    name: "{{ item }}"
    enabled: yes
  loop:
    - xq-api
    - xq-api-hup

- name: Configure nginx base-site
  include_role:
    name: nginx
    tasks_from: base-site
  vars:
    - site:
        name: xq-api
        urls:
          - xq-api.voidlinux.org
        static_root: no
        tls:
          certificate: "{{ xqapi_site_cert_path | default('/dev/null') }}"
          key: "{{ xqapi_site_key_path | default('/dev/null') }}"
          stapling: yes

- name: Install location file
  copy:
    src: root.conf
    dest: /etc/nginx/locations.d/xq-api.voidlinux.org/
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx
