---
buildmaster_version: 0.8.12
buildmaster_user: void-buildmaster
buildmaster_repomgr: void-repomaster

buildmaster_rootdir: /home/void-buildmaster/

buildmaster_machmap:
  x86_64:
    cross: native
    subarch: x86_64
  x86_64-musl:
    cross: native-x86_64-musl
    subarch: x86_64-musl
  i686:
    cross: native-i686
    subarch: i686
  i686-musl:
    cross: native-i686-musl
    subarch: i686-musl
  armv6l:
    cross: armv6hf
    subarch: x86_64
  armv6l-musl:
    cross: armv6hf-musl
    subarch: x86_64-musl
  armv7l:
    cross: armv7hf
    subarch: x86_64
  armv7l-musl:
    cross: armv7hf-musl
    subarch: x86_64-musl
  aarch64:
    cross: aarch64
    subarch: x86_64
  aarch64-musl:
    cross: aarch64-musl
    subarch: x86_64-musl

# The following variable is populated by loading the plaintext file at
# secret/buildmaster_github-secret
#buildmaster_github_secret: GithubSecret!

# The following variable is loaded from
# secret/buildmaster_users.yml and has a structure as shown below
# buildmaster_users:
#   - name: foobar
#     pass: ItsaPassword!

buildmaster_www_servername: build.voidlinux.org

buildmaster_groups:
  - void-repo
