#!/bin/sh

mkdir -p /mirror/man
cd /mirror/man || exit 1

archs="x86_64 x86_64-musl armv7l armv7l-musl"

for arch in $archs; do
    printf "Dumping %s\n" "$arch"
    [ -d "./${arch}" ] || mkdir "./${arch}"
    cd "./${arch}" || exit 1
    [ "${arch}" != "${arch%-musl}" ] && subdir="musl" || subdir=
    xmandump -compress -c cache.json "/mirror/current/${subdir}/${arch}-repodata" "/mirror/current/${subdir}/nonfree/${arch}-repodata"
    cd ../ || exit 1
done

printf "Running makewhatis; this could take a while...\n"
makewhatis $archs
