---
xbps_repository_address: repo-fi.voidlinux.org
xbps_repository_main: https://{{xbps_repository_address}}/current
xbps_repository_nonfree: https://{{xbps_repository_address}}/current/nonfree
xbps_repository_multilib: https://{{xbps_repository_address}}/current/multilib
xbps_repository_multilib_nonfree: https://{{xbps_repository_address}}/current/multilib/nonfree
xbps_repository_port: 443

metal_domain_root: '.m.voidlinux.org'
network_hostname: '{{ inventory_hostname | regex_replace(metal_domain_root, "") | regex_replace("\.", "-") }}'
network_fqdn: '{{ inventory_hostname }}'
network_boot_hosts:
  - name: netauth.voidlinux.org
    addr: 161.35.231.145
  - name: repo-fi.voidlinux.org
    addr: 65.21.160.177

network_input_policy: DROP
network_output_policy: ACCEPT

# We need to allow arbitrary network forwarding due to the requirement
# that we pass traffic between two different overlay networks.  This
# also technically requires net.ipv4.ip_forward, wich is enabled on
# hosts that require this functionality.
network_forward_policy: ACCEPT

network_static_dns_resolvers:
  - 127.0.0.1
