---
grafana:
  site:
    name: grafana
    urls:
      - monitoring.voidlinux.org
    static_root: false
    tls:
      stapling: true
      certificate: /var/lib/acme/live/monitoring.voidlinux.org/fullchain
      key: /var/lib/acme/live/monitoring.voidlinux.org/privkey
