---
- name: Install Packages
  community.general.xbps:
    pkg: NetAuth-ldap
    state: present

- name: Enable Service
  ansible.builtin.service:
    name: netauth-ldap
    state: started
    enabled: true
