---
- name: Disable BuildSlave
  file:
    path: "/var/service/{{ item.service_name | default('void-builder-' + item.mach) }}"
    state: absent
  with_items: "{{ buildslave_buildslaves | json_query(query) }}"
  vars:
    query: "[?zone=='{{ buildslave_zone }}']"
  loop_control:
    label: "{{ item.mach }}"

- name: Remove Service Directories
  file:
    path: "/etc/sv/{{ item.service_name | default('void-builder-' + item.mach) }}"
    state: absent
  with_items: "{{ buildslave_buildslaves | json_query(query) }}"
  vars:
    query: "[?zone=='{{ buildslave_zone }}']"
  loop_control:
    label: "{{ item.mach }}"

- name: Uninstall BuildBot Slave and Dependencies
  xbps:
    pkg:
      - buildbot-slave
    state: absent

- name: Remove Buildslave user ({{ buildslave_user}})
  user:
    name: "{{ buildslave_user }}"
    state: absent
    remove: true

- name: Remove Buildsync user ({{ buildslave_sync_user }})
  user:
    name: "{{ buildslave_sync_user }}"
    state: absent
    remove: true
  when: buildslave_isremote

- name: Remove Builder Directories
  file:
    path: "/{{ buildslave_rootdir }}"
    state: absent

- include_vars: secret/buildslave_credentials.yml

- name: Unconfigure local build mirror
  file:
    path: /etc/xbps.d/99-local-repository.conf
    state: absent
  when: buildslave_zone in buildmaster_remote_zones

- name: Remove sudo policy
  file:
    path: /etc/sudoers.d/buildslave
    state: absent
