#!/bin/sh

cd /var/lib/man-cgi || exit 1

for arch in x86_64 musl/x86_64-musl armv7l musl/armv7l-musl; do
    cd ./${arch#musl/} || exit 1
    xmandump -c cache.json /hostdir/binpkgs/${arch}-repodata
    cd ../ || exit 1
done

makewhatis x86_64 x86_64-musl armv7l armv7l-musl
