---
- name: Disable Service
  runit:
    name: btimefiles
    enabled: false

- name: Uninstall Service (1/2)
  file:
    path: /etc/sv/btimefiles/run
    state: absent

- name: Uninstall Service (2/2)
  file:
    path: /etc/sv/btimefiles
    state: absent

