---
- name: Install configuration
  template:
    src: 40-server.hcl
    dest: /etc/nomad.d/40-server.hcl
    owner: root
    group: root
    mode: 0755
  vars:
    nomad_other_servers: "{{ groups['hashimaster'] | difference([inventory_hostname]) }}"
    nomad_retry_join_servers: "{{ nomad_other_servers | map('extract', void_mesh) | list | sort }}"
  tags: [configure_nomad]
  notify:
    - nomad

- name: Install Secrets
  template:
    src: 30-secrets.hcl
    dest: /etc/nomad.d/
    owner: root
    group: root
    mode: 0400
  notify:
    - nomad
