---
- name: Remove acmetool data root
  file:
    path: /var/lib/acme
    state: absent

- name: Remove renewal crontab
  file:
    path: /etc/cron.d/acmetool
    state: absent

- name: Remove acmetool firewall rules
  file:
    path: /etc/iptables.d/acmetool.rules
    state: absent
  notify:
    - iptables

- name: Remove Service Hooks
  file:
    path: /usr/libexec/acme/hooks/sv_restart
    state: absent
  when: acmetool.services is defined

- name: Remove acmetool
  xbps:
    pkg: acmetool
    state: absent
