---

- name: Unconfigure statrepo server
  file:
    path: /etc/sv/statrepo/conf
    state: absent

- name: Unconfigure pqueryd
  file:
    path: /etc/sv/pqueryd/conf
    state: absent

- name: Remove webroot
  file:
    path: /srv/www/popcorn
    state: absent

- name: Unconfigure nginx
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/locations.d/popcorn.voidlinux.org
    - /etc/nginx/sites-available/popcorn.conf
    - /etc/nginx/sites-enabled/popcorn.conf
    - /etc/iptables.d/nginx-resolvers-popcorn.rules
    - /etc/ip6tables.d/nginx-resolvers-popcorn.6rules
  notify:
    - nginx
    - iptables

- name: Uninstall report script
  file:
    path: /usr/local/bin/popcorn_report
    state: absent

- name: Uninstall firewall rules
  file:
    path: /etc/iptables.d/popcorn.rules
    state: absent
  notify:
    - iptables

- name: Disable services
  runit:
    name: "{{ item }}"
    enabled: no
  with_items:
    - statrepo
    - popcorn-reports
    - pqueryd

- name: Uninstall report service
  file:
    path: /etc/sv/popcorn-reports
    state: absent

- name: Uninstall packages
  xbps:
    pkg:
      - PopCorn-Server
    state: absent
