---
- name: create buildbot worker primary group ({{ buildworker_user }})
  group:
    name: "{{ buildworker_user }}"
    gid: "{{ buildworker_gid }}"
    system: yes

- name: Create buildbot worker user ({{ buildworker_user }})
  user:
    name: "{{ buildworker_user }}"
    state: present
    create_home: no
    system: yes
    uid: "{{ buildworker_uid }}"
    group: "{{ buildworker_user }}"
    groups: "{{ buildworker_groups | join(',') }}"

- name: Install sudo policy
  template:
    src: buildworker.sudoers.j2
    dest: /etc/sudoers.d/buildworker
    owner: root
    group: root
    mode: 0640
