---
- name: Create buildbot worker primary group ({{ buildworker_user }})
  ansible.builtin.group:
    name: "{{ buildworker_user }}"
    gid: "{{ buildworker_gid }}"
    system: true

- name: Create buildbot worker user ({{ buildworker_user }})
  ansible.builtin.user:
    name: "{{ buildworker_user }}"
    state: present
    create_home: false
    system: true
    uid: "{{ buildworker_uid }}"
    group: "{{ buildworker_user }}"
    groups: "{{ buildworker_groups | join(',') }}"

- name: Install sudo policy
  ansible.builtin.template:
    src: buildworker.sudoers.j2
    dest: /etc/sudoers.d/buildworker
    owner: root
    group: root
    mode: "0640"

- name: Create buildroot directory
  ansible.builtin.file:
    path: /buildroot
    state: directory
    owner: "{{ buildworker_uid }}"
    group: "{{ buildworker_gid }}"
    mode: "0755"

- name: Create buildroot subdirectories
  ansible.builtin.file:
    path: "/buildroot/{{ item }}"
    state: directory
    owner: "{{ buildworker_uid }}"
    group: "{{ buildworker_gid }}"
    mode: "0755"
  with_items: "{{ buildworker_archs | default([]) }}"
