---
- name: Install packages
  community.general.xbps:
    pkg: unbound
    state: present

- name: Install config file
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - unbound

- name: Set up control keys
  ansible.builtin.command: unbound-control-setup
  args:
    creates: /etc/unbound/unbound_control.key

- name: Enable Service
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: true
