---
- name: Install cronie
  community.general.xbps:
    pkg: cronie
    state: present

- name: Enable cronie
  ansible.builtin.file:
    src: /etc/sv/crond
    dest: /var/service/crond
    state: link
