---
- name: Install packages
  community.general.xbps:
    pkg: nomad
    state: present
  tags: [install_nomad]

- name: Install base configuration
  ansible.builtin.template:
    src: 25-base.hcl.j2
    dest: /etc/nomad.d/25-base.hcl
    owner: root
    group: root
    mode: "0644"
  notify:
    - nomad

- name: Install Consul Token
  ansible.builtin.template:
    src: 30-consul.hcl
    dest: /etc/nomad.d/30-consul.hcl
    owner: root
    group: root
    mode: "0640"
  notify:
    - nomad

- name: Set Datacenter
  ansible.builtin.template:
    src: 25-dc.hcl
    dest: /etc/nomad.d/25-dc.hcl
    owner: root
    group: root
    mode: "0644"
  notify:
    - nomad

- name: Install Service Config
  ansible.builtin.copy:
    src: conf
    dest: /etc/sv/nomad/conf
    owner: root
    group: root
    mode: "0644"

- name: Enable services
  ansible.builtin.service:
    name: nomad
    enabled: true
    state: started

- name: Install Firewall Rules
  ansible.builtin.copy:
    src: nomad.rules
    dest: /etc/iptables.d/nomad.rules
    owner: root
    group: root
    mode: "0640"
  notify:
    - iptables
