---
- name: Hosts with Static Networking
  hosts: net_static
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - void.network.static

- name: Hosts with Dynamic Networking
  hosts: "!net_static"
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - dhcpcd

- name: Base Machine Configuration
  hosts: all:!unmanaged
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  vars:
    node_exporter_consul_token: "{{lookup('file', 'secret/node_exporter_consul_token')}}"
  roles:
    - void.network.iptables
    - void.network.dns
    - xbps-repoconf
    - sshd
    - mosh
    - unbound
    - chrony
    - netlogon
    - consul
    - node_exporter
