---
- name: Hashicorp Control Plane Servers
  hosts: hashimaster
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  vars:
    nomad_role: server
  roles:
    - consul_server
    - vault
    - nomad_server
    - nomad_client
    - hashi_ws_fw
