---
- name: Generate Network Keys
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Create secret directory
      ansible.builtin.file:
        path: secret/vpn
        state: directory
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_id'] }}"
        mode: "0750"

    - name: Create wireguard keys
      ansible.builtin.shell: wg genkey | tee {{ item }} | wg pubkey > {{ item }}.pub
      args:
        creates: "{{ item }}.pub"
        chdir: secret/vpn
      with_items: "{{ groups['prod'] | difference(groups['unmanaged']) }}"

- name: Install Mesh Network Configuration
  hosts: prod:!unmanaged
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  gather_facts: false
  strategy: ansible.builtin.host_pinned
  roles:
    - void_mesh
