server {
    include /etc/nginx/fragments/ssl.conf;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name repo-default.voidlinux.org
                repo-de.voidlinux.org
                repo-fi.voidlinux.org
                repo-us.voidlinux.org
                repo-fastly.voidlinux.org
                "~^repo-[a-z]{2}\.voidlinux\.org$";
    root /srv/www/mirror;

    location / {
        autoindex on;
    }

    location ~* \.(?:gz|xz)$ {
        expires 1y;
        add_header Cache-Control "public";
    }

    location ~* \.(?:xbps|sig|sig2|iso)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~ (?:x86_64|i686|aarch64|armv6l|armv7l)(?:-musl)?-repodata$ {
        add_header Cache-Control "no-cache";
    }
}

server {
    include /etc/nginx/fragments/ssl.conf;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name docs.voidlinux.org;

    root /srv/www/mirror/docs;
}
