name: infradocs

on:
  pull_request:
    branches:
      - master
    paths:
      - docs/**
  push:
    branches:
      - master
    paths:
      - docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/infradocs
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: latest=false
          labels: |
            org.opencontainers.image.authors=Void Linux team and contributors
            org.opencontainers.image.url=https://voidlinux.org
            org.opencontainers.image.documentation=https://infradocs.voidlinux.org
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.vendor=Void Linux
            org.opencontainers.image.title=Void Linux infrastructure documentation
            org.opencontainers.image.description=infrastructure documentation image for Void Linux

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCHR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: docs
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
