---
- name: Disable BuildBot Service
  file:
    path: /var/service/void-buildmaster
    state: absent

- name: Remove BuildBot Service
  file:
    path: /etc/sv/void-buildmaster
    state: absent

- name: Remove the BuildMaster Root Directory
  file:
    path: "/{{ buildmaster_rootdir }}"
    state: absent

- name: Remove the BuildBot Master user
  user:
    name: "{{ buildmaster_user }}"
    state: absent
    remove: true

- name: Remove deps
  xbps:
    pkg:
      - acl-progs
      - base-devel
      - python-devel
    state: absent

- name: Remove sudo policy
  file:
    path: /etc/sudoers.d/buildmaster
    state: absent
